server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: warn

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:atelier}
    username: ${DB_USER:atelier}
    password: ${DB_PASSWORD:atelier}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  main:
    banner-mode: off

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.example
  launch-browser: true

app:
  scheduler:
    cron: ${CRON:0 0 9 * * *} #every day at 9:00
    zone: "Europe/Moscow"
    max-attempts: ${ATTEMPTS:10}
    retry-delay-seconds: ${RETRY_TIMEOUT:60}

notification:
  port: ${NOTIFICATION_PORT:8080}
  host: ${NOTIFICATION_HOST:http://localhost}

proxy:
  host: ${PROXY_HOST}
  port: ${PROXY_PORT:8080}

telegram:
  enabled: ${TELEGRAM_ENABLED:false}
  token: ${TELEGRAM_TOKEN:default-token}
  chat-id: ${TELEGRAM_CHAT_ID:default-chat}

max:
  enabled: ${MAX_ENABLED:false}
  webhook: ${MAX_WEBHOOK_URL:http://localhost}